nix-env -ibA nixpkgs.asciinema
nix-env -ibA nixpkgs.bat
nix-env -ibA nixpkgs.btop
nix-env -ibA nixpkgs.cargo-cache
nix-env -ibA nixpkgs.cargo-edit
nix-env -ibA nixpkgs.cargo-expand
nix-env -ibA nixpkgs.cargo-nextest
nix-env -ibA nixpkgs.cargo-sweep
nix-env -ibA nixpkgs.cargo-update
nix-env -ibA nixpkgs.cmake
nix-env -ibA nixpkgs.coreutils
nix-env -ibA nixpkgs.delta
nix-env -ibA nixpkgs.deno
nix-env -ibA nixpkgs.docker
nix-env -ibA nixpkgs.du-dust
nix-env -ibA nixpkgs.exercism
nix-env -ibA nixpkgs.fd
nix-env -ibA nixpkgs.fish
nix-env -ibA nixpkgs.fzf
nix-env -ibA nixpkgs.go
nix-env -ibA nixpkgs.just
nix-env -ibA nixpkgs.llvm
nix-env -ibA nixpkgs.lua
nix-env -ibA nixpkgs.lynx
nix-env -ibA nixpkgs.mdbook
nix-env -ibA nixpkgs.mdbook-katex
nix-env -ibA nixpkgs.meilisearch
nix-env -ibA nixpkgs.mpv
nix-env -ibA nixpkgs.ncdu
nix-env -ibA nixpkgs.neofetch
nix-env -ibA nixpkgs.neovim
nix-env -ibA nixpkgs.openconnect
nix-env -ibA nixpkgs.perl
nix-env -ibA nixpkgs.qpdf
nix-env -ibA nixpkgs.R
nix-env -ibA nixpkgs.ripgrep
nix-env -ibA nixpkgs.ruby
nix-env -ibA nixpkgs.sd
nix-env -ibA nixpkgs.speedtest-cli
nix-env -ibA nixpkgs.starship
nix-env -ibA nixpkgs.tealdeer
nix-env -ibA nixpkgs.tmux
nix-env -ibA nixpkgs.unpaper
nix-env -ibA nixpkgs.xdg-ninja
nix-env -ibA nixpkgs.zoxide
