[[plugins]]
repo = 'neoclide/coc-tabnine'
build = 'yarn'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'neoclide/coc-snippets'
build = 'yarn'

[[plugins]]
repo = 'p00f/nvim-ts-rainbow'

# scrollbar
[[plugins]]
repo = 'petertriho/nvim-scrollbar'
[[plugins]]
repo = 'kevinhwang91/nvim-hlslens'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = 'TSUpdate'

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'navarasu/onedark.nvim'