# Command providers - activate on command line enter or specific commands
[[plugins]]
repo = 'junegunn/fzf'
on_event = 'CmdLineEnter'
[[plugins]]
repo = 'junegunn/fzf.vim'
on_event = 'CmdLineEnter'

[[plugins]]
repo = 'numToStr/Comment.nvim'
on_event = 'CmdLineEnter'
hook_post_source = "lua require('Comment').setup {}"

[[plugins]]
repo = 'tpope/vim-fugitive'
on_event = 'CmdLineEnter'


[[plugins]]
repo = 'rcarriga/nvim-notify'
on_event = 'VimEnter'
hook_post_source = "lua require('notify').setup {top_down = false, stages = 'static'}"
[[plugins]]
repo = 'MunifTanjim/nui.nvim'
on_event = 'VimEnter'
[[plugins]]
repo = 'folke/noice.nvim'
on_event = 'VimEnter'
hook_post_source = "lua require('noice').setup {}"

[[plugins]]
repo = 'windwp/nvim-autopairs'
on_event = 'InsertEnter'
hook_post_source = "lua require('nvim-autopairs').setup {}"

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_cmd = 'MarkdownPreview'
build = 'cd app && yarn'

[[plugins]]
repo = 'mhinz/vim-grepper'
on_event = 'CmdLineEnter'

[[plugins]]
repo = 'machakann/vim-swap'
on_event = 'InsertEnter'

## diffview.nvim
[[plugins]]
repo = 'nvim-lua/plenary.nvim'
on_event = 'CmdLineEnter'
[[plugins]]
repo = 'sindrets/diffview.nvim'
on_event = 'CmdLineEnter'
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
on_event = 'CmdLineEnter'
hook_post_source = "lua require('nvim-web-devicons').setup {default = true}"
