# Command providers - activate on command line enter or specific commands
[[plugins]]
repo = 'junegunn/fzf.vim'
on_event = 'CmdLineEnter'

[[plugins]]
repo = 'numToStr/Comment.nvim'
on_event = 'CmdLineEnter'

[[plugins]]
repo = 'windwp/nvim-autopairs'
on_event = 'InsertEnter'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_cmd = 'MarkdownPreview'
build = 'cd app && yarn'

[[plugins]]
repo = 'mhinz/vim-grepper'
on_event = 'CmdLineEnter'

## diffview.nvim
[[plugins]]
repo = 'nvim-lua/plenary.nvim'
on_event = 'CmdLineEnter'
[[plugins]]
repo = 'sindrets/diffview.nvim'
on_event = 'CmdLineEnter'
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
on_event = 'CmdLineEnter'

# Languages support - activate on filetype
[[plugins]]
repo = 'neoclide/coc-json'
name = 'json'
build = 'yarn'
on_ft = 'json'

[[plugins]]
repo = 'fannheyward/coc-markdownlint'
name = 'markdownlint'
build = 'yarn'
on_ft = 'markdown'

[[plugins]]
repo = 'neoclide/coc-solargraph'
name = 'solargraph'
build = 'yarn'
on_ft = ['ruby', 'eruby']

[[plugins]]
repo = 'josa42/coc-lua'
name = 'lua'
build = 'yarn'
on_ft = 'lua'

[[plugins]]
repo = 'preservim/vim-markdown'
name = 'markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'fannheyward/coc-pyright'
on_ft = 'python'
build = 'yarn'

[[plugins]]
repo = 'clangd/coc-clangd'
on_ft = ['c', 'cpp']
build = 'yarn'
