# Command providers - activate on command line enter or specific commands
[[plugins]]
repo = 'junegunn/fzf'
on_event = 'CmdLineEnter'
[[plugins]]
repo = 'junegunn/fzf.vim'
on_event = 'CmdLineEnter'

[[plugins]]
repo = 'numToStr/Comment.nvim'
on_event = 'CmdLineEnter'
hook_post_source = "lua require('Comment').setup {}"


[[plugins]]
repo = 'rcarriga/nvim-notify'
on_event = 'VimEnter'
[[plugins]]
repo = 'MunifTanjim/nui.nvim'
on_event = 'VimEnter'
[[plugins]]
repo = 'folke/noice.nvim'
on_event = 'VimEnter'
hook_post_source = "lua require('noice').setup {}"

[[plugins]]
repo = 'windwp/nvim-autopairs'
on_event = 'InsertEnter'
hook_post_source = "lua require('nvim-autopairs').setup {}"

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_cmd = 'MarkdownPreview'
build = 'cd app && yarn'

[[plugins]]
repo = 'mhinz/vim-grepper'
on_event = 'CmdLineEnter'

[[plugins]]
repo = 'machakann/vim-swap'
on_event = 'InsertEnter'

## diffview.nvim
[[plugins]]
repo = 'nvim-lua/plenary.nvim'
on_event = 'CmdLineEnter'
[[plugins]]
repo = 'sindrets/diffview.nvim'
on_event = 'CmdLineEnter'
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
on_event = 'CmdLineEnter'
hook_post_source = "lua require('nvim-web-devicons').setup {default = true}"

# Languages support - activate on filetype in current directory
[[plugins]]
repo = 'neoclide/coc-json'
name = 'json'
build = 'yarn'
on_event = ['VimEnter', 'DirChanged']
on_if = "system('fd -t f -e json -e jsonc') != ''"

[[plugins]]
repo = 'neoclide/coc-solargraph'
name = 'solargraph'
build = 'yarn'
on_event = ['VimEnter', 'DirChanged']
on_if = "system('fd -t f -e rb') != ''"

[[plugins]]
repo = 'josa42/coc-lua'
name = 'lua'
build = 'yarn'
on_event = ['VimEnter', 'DirChanged']
on_if = "system('fd -t f -e lua') != ''"

[[plugins]]
repo = 'fannheyward/coc-pyright'
on_event = ['VimEnter', 'DirChanged']
on_if = "system('fd -t f -e py') != ''"
build = 'yarn'

[[plugins]]
repo = 'clangd/coc-clangd'
on_event = ['VimEnter', 'DirChanged']
on_if = "system('fd -t f -e c -e cpp -e cc -e cxx -e h -e hpp -e hh') != ''"
build = 'yarn'

[[plugins]]
repo = 'neoclide/coc-tsserver'
on_event = ['VimEnter', 'DirChanged']
on_if = "system('fd -t f -e js -e ts') != ''"
build = 'yarn'

## Markdown
[[plugins]]
repo = 'fannheyward/coc-markdownlint'
name = 'markdownlint'
build = 'yarn'
on_event = ['VimEnter', 'DirChanged']
on_if = "system('fd -t f -e md') != ''"

[[plugins]]
repo = 'preservim/vim-markdown'
name = 'markdown'
on_event = ['VimEnter', 'DirChanged']
on_if = "system('fd -t f -e md') != ''"
