[[plugins]]
repo = 'neoclide/coc-json'
name = 'json'
build = 'yarn'
on_ft = 'json'

[[plugins]]
repo = 'fannheyward/coc-markdownlint'
name = 'markdownlint'
build = 'yarn'
on_ft = 'markdown'

[[plugins]]
repo = 'neoclide/coc-solargraph'
name = 'solargraph'
build = 'yarn'
on_ft = ['ruby', 'eruby']

[[plugins]]
repo = 'josa42/coc-lua'
name = 'lua'
build = 'yarn'
on_ft = 'lua'
