[[plugins]]
repo = 'neoclide/coc-tabnine'
build = 'yarn'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'neoclide/coc-snippets'
build = 'yarn'

[[plugins]]
repo = 'luochen1990/rainbow'

# scrollbar
[[plugins]]
repo = 'petertriho/nvim-scrollbar'
[[plugins]]
repo = 'kevinhwang91/nvim-hlslens'

[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = 'TSUpdate'
